version: '3.8'

services:
  redis:
    image: redis:7.0.11-alpine

  django:
    image: amin_project
    container_name: amin_celery_project
    build:
      context: ./Project
      dockerfile: Dockerfile
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./Project:/app/
    ports:
      - "8000:8000"
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - SECRET_KEY=sdlkfhsdlfhslhdslkdjfsldejfdsl@sldfhglsdfhg
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: ./Project
      dockerfile: Dockerfile
    command: celery --app=Amin_celery_test worker -l INFO
    volumes:
      - ./Project:/app/
    environment:
      - ALLOWED_HOSTS=localhost,127.0.0.1
      - DEBUG=True
      - SECRET_KEY=sdlkfhsdlfhslhdslkdjfsldejfdsl@sldfhglsdfhg
    depends_on:
      - redis
      - django

#  stand_alone_celery:
#    container_name: stand_alone_celery
#    build:
#      context: ./celery_worker
#      dockerfile: Dockerfile
#    command: celery -A celery_base worker -l INFO -Q queue2
#    volumes:
#      - ./celery_worker:/app
#    environment:
#      - BROKER_URL=redis://redis:6379/0
#      - RESULT_BACKEND=redis://redis:6379/0
#    depends_on:
#      - redis
#      - django
